import {
  IconLayoutDashboard,
  IconCash,
  IconPackage,
  IconTemperature,
  IconSpray,
  IconTag,
  IconBooks,
  IconBuilding,
  IconBuildingStore,
  IconUsers,
  IconPackages,
  IconTruck,
  IconCarrot,
  IconChefHat,
  IconSettings,
  IconLicense,
  IconFileText,
  IconAlertTriangle,
  IconCircleCheck,
  IconToolsKitchen2,
  IconLogout,
  IconMapPin,
  IconBolt,
  IconPrinter,
  IconSearch,
  IconCheck,
  IconPencil,
  IconPlus,
  IconX,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronDown,
  IconPhone,
  IconMail,
  IconRobot,
  IconRefresh,
  IconPhoto,
  IconFile,
  IconBluetooth,
  IconFlask,
  IconCircleX,
  IconCalendar,
  IconPalette,
  IconLayoutList,
  IconNote,
  IconTypography,
  IconSalad,
} from '@tabler/icons-react'

// Registro unico delle icone dell'app: una sola fonte di verità.
// La chiave è semantica (di solito il path della rotta).
const REGISTRY = {
  logo: IconToolsKitchen2,
  dashboard: IconLayoutDashboard,
  incassi: IconCash,
  tracciabilita: IconPackage,
  temperature: IconTemperature,
  pulizie: IconSpray,
  etichette: IconTag,
  ddt: IconFileText,
  documentazione: IconBooks,
  struttura: IconBuilding,
  locali: IconBuildingStore,
  utenti: IconUsers,
  anagrafica: IconPackages,
  categorie: IconTag,
  fornitori: IconTruck,
  prodotti: IconCarrot,
  ricette: IconChefHat,
  config: IconSettings,
  'zone-temperatura': IconTemperature,
  'task-pulizie': IconSpray,
  'template-etichette': IconLicense,
  cucina: IconChefHat,
  admin: IconSettings,
  alert: IconAlertTriangle,
  check: IconCircleCheck,
  logout: IconLogout,
  pin: IconMapPin,
  bolt: IconBolt,
  printer: IconPrinter,
  search: IconSearch,
  checkmark: IconCheck,
  pencil: IconPencil,
  plus: IconPlus,
  close: IconX,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronDown: IconChevronDown,
  phone: IconPhone,
  mail: IconMail,
  robot: IconRobot,
  refresh: IconRefresh,
  photo: IconPhoto,
  file: IconFile,
  bluetooth: IconBluetooth,
  test: IconFlask,
  error: IconCircleX,
  calendar: IconCalendar,
  palette: IconPalette,
  layout: IconLayoutList,
  note: IconNote,
  titolo: IconTypography,
  ingredienti: IconSalad,
}

export function Icon({ name, className = 'w-5 h-5', stroke = 1.8, ...rest }) {
  const Cmp = REGISTRY[name] || IconFileText
  return <Cmp className={className} stroke={stroke} {...rest} />
}

export default Icon
